--- 
jobs: 
  build: 
    runs-on: macos-latest
    steps: 
      - 
        uses: actions/checkout@v1
      - 
        name: "Use Node.js"
        uses: actions/setup-node@v1
        with: 
          node-version: 12.x
      - 
        name: "yarn install"
        run: "yarn install"
      - 
        env: 
          CI: true
        name: "yarn test"
        run: "yarn test"
      - 
        name: "yarn build"
        run: "yarn run build --if-present"
      - 
        name: "Add remote origin"
        run: "git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git\n"
      - 
        name: "Deploy to Heroku"
        run: "git push heroku HEAD:master -f\n"
name: "Heroku CI"
true: 
  push: 
    branches: 
      - master
